package com.hospital.swing.enfermeria;

import com.google.gson.*;
import com.hospital.swing.api.ApiClient;
import com.hospital.swing.session.SessionManager;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;

public class CamasPanel extends javax.swing.JPanel {

    private DefaultTableModel modeloCamas;
    private DefaultTableModel modeloOcupadas;

    public CamasPanel() {
        initComponents();
        configurarTablas();
        cargarDatos();
    }

    private void configurarTablas() {
        modeloCamas = new DefaultTableModel(new String[]{"ID", "Número", "Sala", "Estado"}, 0);
        tblCamasDisponibles.setModel(modeloCamas);
        
        modeloOcupadas = new DefaultTableModel(new String[]{"ID Ocup.", "Cama", "Paciente", "Ingreso"}, 0);
        tblOcupacionesActivas.setModel(modeloOcupadas);
        
        // Estilo
        tblCamasDisponibles.getTableHeader().setBackground(new Color(46, 204, 113));
        tblOcupacionesActivas.getTableHeader().setBackground(new Color(231, 76, 60));
    }

    public void cargarDatos() {
        new SwingWorker<Void, Void>() {
            JsonArray jsonCamas = new JsonArray();
            JsonArray jsonOcup = new JsonArray();
    
            @Override protected Void doInBackground() throws Exception {
                try { 
                    JsonElement r1 = ApiClient.get("/camas");
                    if (r1.isJsonArray()) jsonCamas = r1.getAsJsonArray(); 
                } catch (Exception ignored) {}

                try { 
                    JsonElement r2 = ApiClient.get("/camas/ocupaciones/activas"); 
                    if (r2.isJsonArray()) jsonOcup = r2.getAsJsonArray(); 
                } catch (Exception ignored) {}
                return null;
            }

            @Override 
            protected void done() {
                modeloCamas.setRowCount(0);
                for (JsonElement el : jsonCamas) {
                    JsonObject c = el.getAsJsonObject();
                    modeloCamas.addRow(new Object[]{ 
                        c.has("id") ? c.get("id").getAsInt() : (c.has("id_cama") ? c.get("id_cama").getAsInt() : 0),
                        gs(c,"numero"), 
                        gs(c,"sala"), 
                        gs(c,"estado") 
                    });
                }

                modeloOcupadas.setRowCount(0);
                for (JsonElement el : jsonOcup) {
                    JsonObject o = el.getAsJsonObject();
                    modeloOcupadas.addRow(new Object[]{
                        o.get("id_ocupacion").getAsInt(), // Antes decía "id"
                        gs(o, "numero"), 
                        gs(o, "paciente_nombre"), 
                        gs(o, "fecha_ingreso")
                    });
                }
            }
        }.execute();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnAsignarCama = new javax.swing.JButton();
        btnActualizarCamas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCamasDisponibles = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOcupacionesActivas = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnAsignarCama.setText("Asignar Cama");
        btnAsignarCama.addActionListener(this::btnAsignarCamaActionPerformed);

        btnActualizarCamas.setText("Actualizar");

        jLabel1.setText("Camas ocupadas:");

        jLabel2.setText("Camas:");

        tblCamasDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCamasDisponibles);

        jScrollPane4.setViewportView(jScrollPane1);

        tblOcupacionesActivas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblOcupacionesActivas);

        jScrollPane5.setViewportView(jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAsignarCama)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarCamas))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignarCama)
                    .addComponent(btnActualizarCamas))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnAsignarCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCamaActionPerformed
        // TODO add your handling code here:
        int row = tblCamasDisponibles.getSelectedRow();
        if (row < 0) { 
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una cama de la lista."); 
            return; 
        }

        int modelRow = tblCamasDisponibles.convertRowIndexToModel(row);
        int idCama = (int) modeloCamas.getValueAt(modelRow, 0);
        String estado = modeloCamas.getValueAt(modelRow, 3).toString();

        if (!"disponible".equalsIgnoreCase(estado.trim())) {
            JOptionPane.showMessageDialog(this, "Esta cama ya está ocupada o no disponible."); 
            return; 
        }

        String dui = JOptionPane.showInputDialog(this, "Ingrese el DUI del paciente a hospitalizar:");
        if (dui == null || dui.trim().isEmpty()) return;

        btnAsignarCama.setEnabled(false);

        new SwingWorker<Boolean, Void>() {
            String message;

            @Override protected Boolean doInBackground() {
                try {
                    JsonElement rPac = ApiClient.get("/pacientes/dui/" + dui.trim());
                    if (!rPac.isJsonObject()) { 
                        message = "El paciente con DUI " + dui + " no está registrado."; 
                        return false; 
                    }

                    JsonObject pac = rPac.getAsJsonObject();

                    int idPac = pac.has("id") ? pac.get("id").getAsInt() : pac.get("idPaciente").getAsInt();

                    JsonObject oc = new JsonObject();
                    oc.addProperty("idCama", idCama);
                    oc.addProperty("idPaciente", idPac);
                    oc.addProperty("fechaIngreso", java.time.LocalDateTime.now().toString());

                    JsonElement response = ApiClient.post("/camas/ocupar", oc);

                    return response != null;

                } catch (Exception ex) { 
                    message = "Error de conexión: " + ex.getMessage(); 
                    return false; 
                }
            }

            @Override protected void done() {
                btnAsignarCama.setEnabled(true);
                try {
                    if (get()) {
                        JOptionPane.showMessageDialog(CamasPanel.this, "¡Cama asignada exitosamente!");
                        cargarDatos();
                    } else {
                        JOptionPane.showMessageDialog(CamasPanel.this, message != null ? message : "No se pudo asignar la cama.");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(CamasPanel.this, "Error en el proceso.");
                }
            }
        }.execute();
    }//GEN-LAST:event_btnAsignarCamaActionPerformed
    
    private String gs(JsonObject o, String k) {
        return (o.has(k) && !o.get(k).isJsonNull()) ? o.get(k).getAsString() : "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCamas;
    private javax.swing.JButton btnAsignarCama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblCamasDisponibles;
    private javax.swing.JTable tblOcupacionesActivas;
    // End of variables declaration//GEN-END:variables
}

