package com.hospital.swing.enfermeria;

import com.google.gson.*;
import com.hospital.swing.api.ApiClient;
import com.hospital.swing.session.SessionManager;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;

public class CamasPanel extends javax.swing.JPanel {

    private DefaultTableModel modeloCamas;
    private DefaultTableModel modeloOcupadas;

    public CamasPanel() {
        initComponents();
        configurarTablas();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnAsignar = new javax.swing.JButton();
        btnDarAlta = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        btnAsignar.setText("Asignar Cama");
        btnAsignar.addActionListener(this::btnAsignarActionPerformed);

        btnDarAlta.setText("Dar de Alta");
        btnDarAlta.addActionListener(this::btnDarAltaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAsignar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(btnDarAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignar)
                    .addComponent(btnDarAlta))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTablas() {
        // Tabla camas disponibles
        modeloCamas = new DefaultTableModel(
            new String[]{"ID Cama", "Número", "Tipo", "Estado"}, 0
        ) { public boolean isCellEditable(int r, int c) { return false; } };
        jTable1.setModel(modeloCamas);
        jTable1.setRowHeight(24);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setBackground(new Color(34, 139, 34));
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override public java.awt.Component getTableCellRendererComponent(
                    JTable t, Object v, boolean sel, boolean foc, int r, int c) {
                super.getTableCellRendererComponent(t, v, sel, foc, r, c);
                String estado = modeloCamas.getValueAt(
                    t.convertRowIndexToModel(r), 3).toString();
                if (!sel) setBackground("disponible".equalsIgnoreCase(estado)
                    ? new Color(200, 255, 200) : new Color(255, 220, 220));
                return this;
            }
        });

        // Tabla ocupaciones activas
        modeloOcupadas = new DefaultTableModel(
            new String[]{"ID Ocup.", "Cama", "Paciente", "Fecha Ingreso"}, 0
        ) { public boolean isCellEditable(int r, int c) { return false; } };
        jTable3.setModel(modeloOcupadas);
        jTable3.setRowHeight(24);
        jTable3.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable3.getTableHeader().setBackground(new Color(180, 40, 40));
        jTable3.getTableHeader().setForeground(Color.WHITE);
    }
    public void cargarDatos() {
        new SwingWorker<Void, Void>() {
            JsonArray camas = new JsonArray();
            JsonArray ocupaciones = new JsonArray();
            @Override protected Void doInBackground() {
                try { JsonElement r = ApiClient.get("/camas");
                    if (r.isJsonArray()) camas = r.getAsJsonArray(); } catch (Exception ignored) {}
                try { JsonElement r = ApiClient.get("/ocupaciones/activas");
                    if (r.isJsonArray()) ocupaciones = r.getAsJsonArray(); } catch (Exception ignored) {}
                return null;
            }
            @Override protected void done() {
                modeloCamas.setRowCount(0);
                for (JsonElement el : camas) {
                    JsonObject c = el.getAsJsonObject();
                    modeloCamas.addRow(new Object[]{
                        c.get("id_cama").getAsInt(),
                        gs(c,"numero"), gs(c,"sala"), gs(c,"estado") // Usar nombres de la DB
                    });
                }
                modeloOcupadas.setRowCount(0);
                for (JsonElement el : ocupaciones) {
                    JsonObject o = el.getAsJsonObject();
                    modeloOcupadas.addRow(new Object[]{
                        o.get("id_ocupacion").getAsInt(),
                        gs(o,"numero"), gs(o,"paciente_nombre"), gs(o,"fecha_ingreso")
                    });
                }
            }
        }.execute();
    }
    
    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Selecciona una cama."); return; }
        int idCama = (int) modeloCamas.getValueAt(jTable1.convertRowIndexToModel(row), 0);
        String estado = (String) modeloCamas.getValueAt(jTable1.convertRowIndexToModel(row), 3);
        if (!"disponible".equalsIgnoreCase(estado)) {
            JOptionPane.showMessageDialog(this, "La cama no está disponible."); return; }
        String dui = JOptionPane.showInputDialog(this, "DUI del paciente:");
        if (dui == null || dui.trim().isEmpty()) return;
        new SwingWorker<Void, Void>() {
            String err;
            @Override protected Void doInBackground() {
                try {
                    JsonElement rPac = ApiClient.get("/pacientes/dui/" + dui.trim());
                    if (!rPac.isJsonObject()) { err = "Paciente no encontrado."; return null; }
                    int idPac = rPac.getAsJsonObject().get("idPaciente").getAsInt();
                    JsonObject oc = new JsonObject();
                    oc.addProperty("idCama",     idCama);
                    oc.addProperty("idPaciente", idPac);
                    oc.addProperty("idUsuario",  SessionManager.getInstance().getIdUsuario());
                    ApiClient.post("/ocupaciones", oc);
                } catch (Exception ex) { err = ex.getMessage(); }
                return null;
            }
            @Override protected void done() {
                if (err != null) JOptionPane.showMessageDialog(CamasPanel.this, "Error: " + err);
                else { JOptionPane.showMessageDialog(CamasPanel.this, "Cama asignada."); cargarDatos(); }
            }
        }.execute();
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnDarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarAltaActionPerformed
        // TODO add your handling code here:
        int row = jTable3.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Selecciona una ocupación."); return; }
        int idOcup = (int) modeloOcupadas.getValueAt(jTable3.convertRowIndexToModel(row), 0);
        String pac  = (String) modeloOcupadas.getValueAt(jTable3.convertRowIndexToModel(row), 2);
        if (JOptionPane.showConfirmDialog(this, "¿Dar de alta a: " + pac + "?",
                "Confirmar Alta", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) return;
        new SwingWorker<Void, Void>() {
            String err;
            @Override protected Void doInBackground() {
                try { ApiClient.put("/ocupaciones/" + idOcup + "/alta", new JsonObject()); }
                catch (Exception ex) { err = ex.getMessage(); }
                return null;
            }
            @Override protected void done() {
                if (err != null) JOptionPane.showMessageDialog(CamasPanel.this, "Error: " + err);
                else { JOptionPane.showMessageDialog(CamasPanel.this, "Alta registrada."); cargarDatos(); }
            }
        }.execute();
    }//GEN-LAST:event_btnDarAltaActionPerformed
    
    private String gs(JsonObject o, String k) {
        return (o.has(k) && !o.get(k).isJsonNull()) ? o.get(k).getAsString() : "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnDarAlta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
