package com.hospital.swing.enfermeria;

import com.google.gson.*;
import com.hospital.swing.api.ApiClient;
import com.hospital.swing.session.SessionManager;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;

public class MedicamentosPanel extends javax.swing.JPanel {

    private DefaultTableModel modelo;
    private int idExpediente = -1;

    public MedicamentosPanel() {
        initComponents();
        configurarTabla();
        cargarMedicamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDUI = new javax.swing.JTextField();
        cmbMedicamentos = new javax.swing.JComboBox<>();
        txtDosis = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblPaciente = new javax.swing.JLabel();

        txtDUI.setText("DUI");
        txtDUI.addActionListener(this::txtDUIActionPerformed);

        cmbMedicamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMedicamentos.addActionListener(this::cmbMedicamentosActionPerformed);

        txtDosis.setText("Dosis");
        txtDosis.addActionListener(this::txtDosisActionPerformed);

        txtCantidad.setText("Cantidad");
        txtCantidad.addActionListener(this::txtCantidadActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        lblPaciente.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPaciente)
                                .addGap(25, 25, 25)
                                .addComponent(btnRegistrar)))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDUI, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPaciente)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla() {
        modelo = new DefaultTableModel(
            new String[]{"Fecha", "Medicamento", "Dosis", "Cantidad", "Enfermero"}, 0
        ) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        jTable1.setModel(modelo);
        jTable1.setRowHeight(24);
        jTable1.getTableHeader().setBackground(new Color(30, 80, 150));
        jTable1.getTableHeader().setForeground(Color.WHITE);
        txtDosis.setToolTipText("Dosis (ej: 500mg)");
        txtCantidad.setToolTipText("Cantidad administrada");
    }

    private void cargarMedicamentos() {

        new SwingWorker<JsonArray, Void>() {

            @Override
            protected JsonArray doInBackground() {
                try {
                    JsonElement r = ApiClient.get("/productos");
                    return r.isJsonArray() ? r.getAsJsonArray() : new JsonArray();
                } catch (Exception ex) {
                    return new JsonArray();
                }
            }

            @Override
            protected void done() {
                try {
                    cmbMedicamentos.removeAllItems();
                    mapaMedicamentos.clear();

                    for (JsonElement el : get()) {
                        JsonObject p = el.getAsJsonObject();
                        int id = p.get("idProducto").getAsInt();
                        String nombre = gs(p, "nombre");

                        cmbMedicamentos.addItem(nombre);
                        mapaMedicamentos.put(nombre, id);
                    }

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }.execute();
    }
    private void txtDUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDUIActionPerformed
        // TODO add your handling code here:
        btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_txtDUIActionPerformed

    private void cmbMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMedicamentosActionPerformed

    private void txtDosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDosisActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String dui = txtDUI.getText().trim();
        if (dui.isEmpty()) { JOptionPane.showMessageDialog(this, "Ingresa el DUI."); return; }
        btnBuscar.setEnabled(false);
        new SwingWorker<Void, Void>() {
            String err;
            @Override protected Void doInBackground() {
                try {
                    JsonElement rPac = ApiClient.get("/pacientes/dui/" + dui);
                    if (!rPac.isJsonObject()) { err = "Paciente no encontrado."; return null; }
                    JsonObject pac = rPac.getAsJsonObject();
                    int idPac = pac.get("idPaciente").getAsInt();
                    String nombre = gs(pac, "nombre") + " " + gs(pac, "apellido");
                    JsonElement rExp = ApiClient.get("/expedientes/paciente/" + idPac);
                    JsonObject exp = rExp.isJsonArray()
                        ? rExp.getAsJsonArray().get(0).getAsJsonObject()
                        : rExp.getAsJsonObject();
                    idExpediente = exp.get("idExpediente").getAsInt();
                    SwingUtilities.invokeLater(() -> {
                        lblPaciente.setText("Paciente: " + nombre);
                        lblPaciente.setForeground(new Color(30, 80, 150));
                        btnRegistrar.setEnabled(true);
                    });
                    JsonElement rMed = ApiClient.get("/administracion-medicamentos/expediente/" + idExpediente);
                    JsonArray lista = rMed.isJsonArray() ? rMed.getAsJsonArray() : new JsonArray();
                    SwingUtilities.invokeLater(() -> {
                        modelo.setRowCount(0);
                        for (JsonElement el : lista) {
                            JsonObject m = el.getAsJsonObject();
                            modelo.addRow(new Object[]{
                                gs(m,"fechaAdministracion"), gs(m,"medicamento"),
                                gs(m,"dosis"), gs(m,"cantidad"), gs(m,"enfermero")
                            });
                        }
                    });
                } catch (Exception ex) { err = ex.getMessage(); }
                return null;
            }
            @Override protected void done() {
                btnBuscar.setEnabled(true);
                if (err != null) {
                    lblPaciente.setText(err);
                    lblPaciente.setForeground(Color.RED);
                    idExpediente = -1; btnRegistrar.setEnabled(false);
                }
            }
        }.execute();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if (idExpediente < 0 || cmbMedicamentos.getSelectedItem() == null) return;
        btnRegistrar.setEnabled(false);
        String nombreMed = (String) cmbMedicamentos.getSelectedItem();
        Integer idProducto = mapaMedicamentos.get(nombreMed);

        if (idProducto == null) {
            JOptionPane.showMessageDialog(this, "Medicamento inválido.");
            return;
        }

        new SwingWorker<Void, Void>() {
            String err;
            @Override protected Void doInBackground() {
                try {
                    JsonObject m = new JsonObject();
                    m.addProperty("idExpediente", idExpediente);
                    m.addProperty("idProducto",   idProducto);
                    m.addProperty("dosis",        txtDosis.getText().trim());
                    m.addProperty("cantidad",     txtCantidad.getText().trim());
                    m.addProperty("idUsuario",    SessionManager.getInstance().getIdUsuario());
                    ApiClient.post("/administracion-medicamentos", m);
                } catch (Exception ex) { err = ex.getMessage(); }
                return null;
            }
            @Override protected void done() {
                btnRegistrar.setEnabled(true);
                if (err != null) JOptionPane.showMessageDialog(MedicamentosPanel.this, "Error: " + err);
                else {
                    JOptionPane.showMessageDialog(MedicamentosPanel.this, "Medicamento registrado.");
                    txtDosis.setText(""); txtCantidad.setText("");
                    btnBuscarActionPerformed(null);
                }
            }
        }.execute();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private String gs(JsonObject o, String k) {
        return (o.has(k) && !o.get(k).isJsonNull()) ? o.get(k).getAsString() : "";
    }
    private java.util.Map<String, Integer> mapaMedicamentos = new java.util.HashMap<>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbMedicamentos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDUI;
    private javax.swing.JTextField txtDosis;
    // End of variables declaration//GEN-END:variables
}
