package com.hospital.swing.enfermeria;

import com.google.gson.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;

public class SignosChartDialog extends javax.swing.JDialog {

    private JsonArray historial;
    private String nombrePaciente;

    public SignosChartDialog(java.awt.Frame parent, String nombre, JsonArray datos) {
        super(parent, true);
        this.nombrePaciente = nombre;
        this.historial = (datos != null) ? datos : new JsonArray();
        
        initComponents();
        lblPacienteDetail.setText("Historial de: " + nombrePaciente);
        setLocationRelativeTo(parent);
    }

    private class ChartPainter extends JPanel {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (historial.size() < 1) return;

            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            int m = 50; 
            int w = getWidth() - 2 * m;
            int h = getHeight() - 2 * m;

            // Ejes
            g2.setColor(Color.BLACK);
            g2.drawLine(m, m, m, m + h); // Y
            g2.drawLine(m, m + h, m + w, m + h); // X

            double xStep = (historial.size() > 1) ? (double) w / (historial.size() - 1) : 0;

            if (chkShowTemp.isSelected()) drawLine(g2, "temperatura", Color.RED, m, h, xStep, 10);
            if (chkShowFC.isSelected()) drawLine(g2, "frecuenciaCardiaca", Color.BLUE, m, h, xStep, 2);
            if (chkShowPeso.isSelected()) drawLine(g2, "peso", new Color(0, 120, 0), m, h, xStep, 2);
        }

        private void drawLine(Graphics2D g2, String key, Color c, int m, int h, double xStep, int scale) {
            g2.setColor(c);
            int prevX = 0, prevY = 0;
            for (int i = 0; i < historial.size(); i++) {
                double val = extraer(historial.get(i).getAsJsonObject(), key);
                int x = m + (int)(i * xStep);
                int y = (m + h) - (int)(val * scale); // Escala visual simple

                if (i > 0) g2.drawLine(prevX, prevY, x, y);
                g2.fillOval(x - 3, y - 3, 6, 6);
                prevX = x; prevY = y;
            }
        }

        private double extraer(JsonObject o, String k) {
            try { return Double.parseDouble(o.get(k).getAsString().replaceAll("[^0-9.]", "")); }
            catch (Exception e) { return 0; }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPacienteDetail = new javax.swing.JLabel();
        pnlChartArea = new javax.swing.JPanel();
        pnlFilters = new javax.swing.JPanel();
        chkShowTemp = new javax.swing.JCheckBox();
        chkShowFC = new javax.swing.JCheckBox();
        chkShowPeso = new javax.swing.JCheckBox();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gráfico de Evolución Médica");

        lblPacienteDetail.setText("Paciente:");

        pnlChartArea.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlChartAreaLayout = new javax.swing.GroupLayout(pnlChartArea);
        pnlChartArea.setLayout(pnlChartAreaLayout);
        pnlChartAreaLayout.setHorizontalGroup(
            pnlChartAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        pnlChartAreaLayout.setVerticalGroup(
            pnlChartAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        chkShowTemp.setText("Temperatura");
        chkShowTemp.addActionListener(this::chkShowTempActionPerformed);

        chkShowFC.setText("Frec. Cardíaca");
        chkShowFC.addActionListener(this::chkShowFCActionPerformed);

        chkShowPeso.setText("Peso");
        chkShowPeso.addActionListener(this::chkShowPesoActionPerformed);

        javax.swing.GroupLayout pnlFiltersLayout = new javax.swing.GroupLayout(pnlFilters);
        pnlFilters.setLayout(pnlFiltersLayout);
        pnlFiltersLayout.setHorizontalGroup(
            pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkShowTemp)
                .addGap(35, 35, 35)
                .addComponent(chkShowFC)
                .addGap(35, 35, 35)
                .addComponent(chkShowPeso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFiltersLayout.setVerticalGroup(
            pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltersLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkShowTemp)
                    .addComponent(chkShowFC)
                    .addComponent(chkShowPeso))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnClose.setText("Cerrar Ventana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                        .addComponent(lblPacienteDetail)
                        .addGap(191, 191, 191))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnClose))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pnlFilters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnlChartArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblPacienteDetail))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlChartArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkShowTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowTempActionPerformed
        // TODO add your handling code here:
        pnlChartArea.repaint();
    }//GEN-LAST:event_chkShowTempActionPerformed

    private void chkShowFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowFCActionPerformed
        // TODO add your handling code here:
        pnlChartArea.repaint();
    }//GEN-LAST:event_chkShowFCActionPerformed

    private void chkShowPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPesoActionPerformed
        // TODO add your handling code here:
        pnlChartArea.repaint();
    }//GEN-LAST:event_chkShowPesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(SignosChartDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                com.google.gson.JsonArray datosPrueba = new com.google.gson.JsonArray();
                
                SignosChartDialog dialog = new SignosChartDialog(new javax.swing.JFrame(), "Paciente de Prueba", datosPrueba);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JCheckBox chkShowFC;
    private javax.swing.JCheckBox chkShowPeso;
    private javax.swing.JCheckBox chkShowTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPacienteDetail;
    private javax.swing.JPanel pnlChartArea;
    private javax.swing.JPanel pnlFilters;
    // End of variables declaration//GEN-END:variables
}
