package com.hospital.swing.enfermeria;

import com.google.gson.*;
import com.hospital.swing.api.ApiClient;
import com.hospital.swing.session.SessionManager;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;

public class SignosVitalesPanel extends javax.swing.JPanel {

    private DefaultTableModel modelo;
    private int idExpediente = -1;

    public SignosVitalesPanel() {
        initComponents();
        configurarTabla();
        lblPaciente.setText("Seleccione un paciente");
    }

    private void configurarTabla() {
        modelo = new DefaultTableModel(
            new String[]{"Fecha", "FC", "FR", "Temp", "PA", "O2", "Peso", "Talla"}, 0
        ) {
            @Override
            public boolean isCellEditable(int r, int c) { return false; }
        };
        jTable1.setModel(modelo);
        jTable1.setRowHeight(24);
        jTable1.getTableHeader().setBackground(new Color(30, 80, 150));
        jTable1.getTableHeader().setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        txtDUI = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtFC = new javax.swing.JTextField();
        txtFR = new javax.swing.JTextField();
        txtTemp = new javax.swing.JTextField();
        txtPA = new javax.swing.JTextField();
        txtSat = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtTalla = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblPaciente = new javax.swing.JLabel();

        txtDUI.setText("DUI");
        txtDUI.addActionListener(this::txtDUIActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        txtFC.setText("FC");
        txtFC.addActionListener(this::txtFCActionPerformed);

        txtFR.setText("FR");
        txtFR.addActionListener(this::txtFRActionPerformed);

        txtTemp.setText("Temperatura");
        txtTemp.addActionListener(this::txtTempActionPerformed);

        txtPA.setText("PA");
        txtPA.addActionListener(this::txtPAActionPerformed);

        txtSat.setText("Sat");
        txtSat.addActionListener(this::txtSatActionPerformed);

        txtPeso.setText("Peso");
        txtPeso.addActionListener(this::txtPesoActionPerformed);

        txtTalla.setText("Talla");
        txtTalla.addActionListener(this::txtTallaActionPerformed);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblPaciente.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtDUI, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnBuscar)
                                    .addGap(30, 30, 30)
                                    .addComponent(lblPaciente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRegistrar)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jSplitPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnRegistrar)
                    .addComponent(lblPaciente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDUIActionPerformed
        // TODO add your handling code here:
         btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_txtDUIActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
         String dui = txtDUI.getText().trim();
        if (dui.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un DUI para buscar.");
            return;
        }

        new SwingWorker<Void, Void>() {
            String nombrePac = "";
            JsonArray historial = new JsonArray();
            String errorMsg = null;

            @Override protected Void doInBackground() throws Exception {
                try {
                    // 1. Buscar expediente por DUI
                    JsonElement resE = ApiClient.get("/expedientes/buscar-dui/" + dui);
                    if (resE.isJsonObject()) {
                        JsonObject exp = resE.getAsJsonObject();
                        idExpediente = exp.get("id").getAsInt();
                        nombrePac = exp.get("nombrePaciente").getAsString();

                        // 2. Cargar historial de signos vitales
                        JsonElement resS = ApiClient.get("/signosvitales/expediente/" + idExpediente);
                        if (resS.isJsonArray()) {
                            historial = resS.getAsJsonArray();
                        }
                    } else {
                        idExpediente = -1;
                    }
                } catch (Exception e) {
                    errorMsg = e.getMessage();
                }
                return null;
            }

            @Override protected void done() {
                if (idExpediente != -1) {
                    lblPaciente.setText("Paciente: " + nombrePac);
                    lblPaciente.setForeground(new Color(0, 102, 0));
                    modelo.setRowCount(0);
                    for (JsonElement el : historial) {
                        JsonObject s = el.getAsJsonObject();
                        modelo.addRow(new Object[]{
                            gs(s, "fechaRegistro"), gs(s, "frecuenciaCardiaca"), 
                            gs(s, "frecuenciaRespiratoria"), gs(s, "temperatura"), 
                            gs(s, "presionArterial"), gs(s, "saturacionOxigeno"), 
                            gs(s, "peso"), gs(s, "talla")
                        });
                    }
                } else {
                    lblPaciente.setText("No se encontró el expediente.");
                    lblPaciente.setForeground(Color.RED);
                    modelo.setRowCount(0);
                    if (errorMsg != null) System.err.println("Error: " + errorMsg);
                }
            }
        }.execute();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCActionPerformed

    private void txtFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFRActionPerformed

    private void txtTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempActionPerformed

    private void txtPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAActionPerformed

    private void txtSatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSatActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void txtTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTallaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if (idExpediente == -1) {
            JOptionPane.showMessageDialog(this, "Primero debe buscar y seleccionar un paciente.");
            return;
        }

        // Crear el objeto para el API
        JsonObject sv = new JsonObject();
        sv.addProperty("IdExpediente", idExpediente);
        sv.addProperty("FrecuenciaCardiaca", txtFC.getText().trim());
        sv.addProperty("FrecuenciaRespiratoria", txtFR.getText().trim());
        sv.addProperty("Temperatura", txtTemp.getText().trim());
        sv.addProperty("PresionArterial", txtPA.getText().trim());
        sv.addProperty("SaturacionOxigeno", txtSat.getText().trim());
        sv.addProperty("Peso", txtPeso.getText().trim());
        sv.addProperty("Talla", txtTalla.getText().trim());

        new SwingWorker<Void, Void>() {
            String errorMsg = null;
            @Override protected Void doInBackground() throws Exception {
                try {
                    ApiClient.post("/signosvitales", sv);
                } catch (Exception e) {
                    errorMsg = e.getMessage();
                }
                return null;
            }
            @Override protected void done() {
                if (errorMsg == null) {
                    JOptionPane.showMessageDialog(SignosVitalesPanel.this, "Signos vitales registrados correctamente.");
                    limpiarCampos();
                    btnBuscarActionPerformed(null); // Recargar la tabla automáticamente
                } else {
                    JOptionPane.showMessageDialog(SignosVitalesPanel.this, "Error al registrar: " + errorMsg);
                }
            }
        }.execute();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void limpiarCampos() {
        txtFC.setText("");
        txtFR.setText("");
        txtTemp.setText("");
        txtPA.setText("");
        txtSat.setText("");
        txtPeso.setText("");
        txtTalla.setText("");
    }

    private String gs(JsonObject o, String k) {
        return (o.has(k) && !o.get(k).isJsonNull()) ? o.get(k).getAsString() : "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JTextField txtDUI;
    private javax.swing.JTextField txtFC;
    private javax.swing.JTextField txtFR;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtSat;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
