package com.hospital.swing.main;

import com.hospital.swing.administracion.*;
import com.hospital.swing.bodega.BodegaPanel;
import com.hospital.swing.enfermeria.*;
import com.hospital.swing.login.LoginFrame;
import com.hospital.swing.session.SessionManager;
import javax.swing.*;
import java.awt.*;

public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(MainFrame.class.getName());

    public MainFrame() {
        initComponents();
        configurarVentana();
        configurarSesion();
        configurarNavegacion();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Sistema Hospitalario");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);
        jPanel1.add(btnCerrarSesion, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("Usuarios");
        jPanel2.add(jButton1);

        jButton3.setText("Finanzas");
        jPanel2.add(jButton3);

        jButton2.setText("Inventario");
        jPanel2.add(jButton2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarVentana() {
        setTitle("Sistema Hospitalario");
        setSize(1150, 720);
        setLocationRelativeTo(null);
    }

    private void configurarSesion() {
        String nombre = SessionManager.getInstance().getNombreUsuario();
        String rol    = SessionManager.getInstance().getRolNombre();
        jLabel1.setText("  " + nombre);
        jLabel2.setText("  Rol: " + rol);
    }

    private void configurarNavegacion() {
        String rol = SessionManager.getInstance().getRolNombre();
        jPanel2.removeAll();
        jPanel3.removeAll();
        CardLayout cl = (CardLayout) jPanel3.getLayout();

        if (rol.equalsIgnoreCase("Bodega")) {
            BodegaPanel bodega = new BodegaPanel();
            jPanel3.add(bodega, "bodega");
            jButton1.setText("Inventario");
            jButton1.addActionListener(e -> cl.show(jPanel3, "bodega"));
            estilizarBoton(jButton1); jPanel2.add(jButton1);
            jButton2.setVisible(false); jButton3.setVisible(false);

        } else if (rol.toLowerCase().contains("administra")) {
            UsuariosPanel usuarios       = new UsuariosPanel();
            InventarioAdminPanel inv     = new InventarioAdminPanel();
            FinancieroPanel financiero   = new FinancieroPanel();
            jPanel3.add(usuarios,   "usuarios");
            jPanel3.add(inv,        "inventario");
            jPanel3.add(financiero, "financiero");
            jButton1.setText("Usuarios");
            jButton1.addActionListener(e -> { cl.show(jPanel3, "usuarios"); resaltarBoton(jButton1); });
            jButton3.setText("Inventario");
            jButton3.addActionListener(e -> { cl.show(jPanel3, "inventario"); resaltarBoton(jButton3); });
            jButton2.setText("Financiero");
            jButton2.addActionListener(e -> { cl.show(jPanel3, "financiero"); resaltarBoton(jButton2); });
            estilizarBoton(jButton1); estilizarBoton(jButton3); estilizarBoton(jButton2);
            jPanel2.add(jButton1); jPanel2.add(jButton3); jPanel2.add(jButton2);

        } else if (rol.toLowerCase().contains("enfermer")) {
            SignosVitalesPanel signos   = new SignosVitalesPanel();
            MedicamentosPanel meds     = new MedicamentosPanel();
            CamasPanel camas           = new CamasPanel();
            jPanel3.add(signos, "signos");
            jPanel3.add(meds,   "medicamentos");
            jPanel3.add(camas,  "camas");
            jButton1.setText("Signos Vitales");
            jButton1.addActionListener(e -> { cl.show(jPanel3, "signos"); resaltarBoton(jButton1); });
            jButton3.setText("Medicamentos");
            jButton3.addActionListener(e -> { cl.show(jPanel3, "medicamentos"); resaltarBoton(jButton3); });
            jButton2.setText("Camas");
            jButton2.addActionListener(e -> { cl.show(jPanel3, "camas"); resaltarBoton(jButton2); });
            estilizarBoton(jButton1); estilizarBoton(jButton3); estilizarBoton(jButton2);
            jPanel2.add(jButton1); jPanel2.add(jButton3); jPanel2.add(jButton2);
        }

        jPanel2.revalidate(); jPanel2.repaint();
        cl.first(jPanel3);
    }

    private void estilizarBoton(JButton btn) {
        btn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 44));
        btn.setAlignmentX(Component.CENTER_ALIGNMENT);
        btn.setBackground(new Color(45, 85, 165));
        btn.setForeground(Color.WHITE);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn.setHorizontalAlignment(SwingConstants.LEFT);
        btn.setBorder(BorderFactory.createEmptyBorder(8, 12, 8, 8));
    }

    private void resaltarBoton(JButton activo) {
        for (java.awt.Component c : jPanel2.getComponents())
            if (c instanceof JButton)
                ((JButton) c).setBackground(new Color(45, 85, 165));
        activo.setBackground(new Color(20, 60, 130));
    }
    
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        SessionManager.getInstance().cerrarSesion();
        dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
