package com.hospital.swing.login;

import com.google.gson.*;
import com.hospital.swing.api.ApiClient;
import com.hospital.swing.main.MainFrame;
import com.hospital.swing.session.SessionManager;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

public class LoginFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    public LoginFrame() {
        initComponents();
        setTitle("Hospital - Iniciar Sesión");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUsuario.setText("Usuario");
        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);

        txtPassword.setText("Contraseña");
        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        btnLogin.setText("Ingresar");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        jLabel1.setText("Sistema Hospitalario");

        lblStatus.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(btnLogin))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsuario)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addGap(13, 13, 13)
                .addComponent(btnLogin)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
        btnLoginActionPerformed(evt);
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String usuario  = txtUsuario.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();

        if (usuario.isEmpty() || password.isEmpty()) {
            lblStatus.setText("Ingresa usuario y contraseña."); 
            return; 
        }

        btnLogin.setEnabled(false);
        btnLogin.setText("...");
        lblStatus.setText(" ");

        new SwingWorker<Void, Void>() {
            String err;

            @Override protected Void doInBackground() {
                try {
                    JsonObject body = new JsonObject();
                    body.addProperty("usuario", usuario);
                    body.addProperty("contraseña", password);

                    // 1. Llamada al API
                    JsonElement res = ApiClient.post("/usuarios/login", body);

                    if (res == null || res.isJsonNull()) {
                        err = "El servidor devolvió una respuesta vacía.";
                        return null;
                    }

                    JsonObject obj = res.getAsJsonObject();
                    System.out.println("JSON RECIBIDO: " + obj.toString());

                    // 1. El Token está en la raíz
                    String token = obj.has("token") ? obj.get("token").getAsString() : "";

                    // 2. Los demás datos están DENTRO del objeto "usuario"
                    if (obj.has("usuario") && !obj.get("usuario").isJsonNull()) {
                        JsonObject userObj = obj.getAsJsonObject("usuario"); // Entramos al sub-objeto

                        // Extraemos los datos usando las claves que vimos en tu consola: "id", "nombre", "nombreRol"
                        int idUsr = userObj.get("id").getAsInt();
                        String nombre = userObj.get("nombre").getAsString();
                        String rol = userObj.get("nombreRol").getAsString();

                        // 3. Validación de Roles (Ajustada a "Administrador")
                        if (rol.equalsIgnoreCase("Administrador")) {
                            // OK
                        } else if (rol.equalsIgnoreCase("Enfermería")) {
                            // OK
                        } else if (rol.equalsIgnoreCase("Bodega") || rol.equalsIgnoreCase("Farmacéutico")) {
                            // OK
                        } else {
                            err = "Acceso denegado para el rol: " + rol;
                            return null;
                        }

                        // 4. Iniciar sesión con los datos extraídos
                        SessionManager.getInstance().iniciarSesion(token, rol, idUsr, nombre);

                    } else {
                        err = "El servidor no envió el objeto 'usuario'.";
                        return null;
                    }
    
                } catch (Exception ex) { 
                    err = "Error: " + ex.getMessage(); 
                }
                return null;
            }

            @Override protected void done() {
                btnLogin.setEnabled(true); 
                btnLogin.setText("INGRESAR");
                if (err != null) { 
                    lblStatus.setText(err); 
                } else if (SessionManager.getInstance().estaAutenticado()) {
                    dispose(); 
                    new MainFrame().setVisible(true); 
                }
            }
        }.execute();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
