package com.hospital.swing.bodega;

import com.google.gson.*;
import com.hospital.swing.api.ApiClient;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;

public class BodegaPanel extends javax.swing.JPanel {

    private DefaultTableModel modelo;

    public BodegaPanel() {
        initComponents();
        configurarTabla();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscador = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        txtBuscador.setText("Buscador");
        txtBuscador.addActionListener(this::txtBuscadorActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla() {
        modelo = new DefaultTableModel(
            new String[]{"ID", "Nombre", "Tipo", "Unidad", "Precio", "Vencimiento", "Estado", "Stock"}, 0
        ) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        jTable1.setModel(modelo);
        jTable1.setRowHeight(26);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setBackground(new Color(30, 80, 150));
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.setAutoCreateRowSorter(true);
    }
    private void cargarProductos() {
        new SwingWorker<JsonArray, Void>() {
            @Override
            protected JsonArray doInBackground() {
                try {
                    // RUTA: /productos (porque el controlador es ProductosController)
                    JsonElement r = ApiClient.get("/productos"); 
                    return r.isJsonArray() ? r.getAsJsonArray() : new JsonArray();
                } catch (Exception ex) {
                    return new JsonArray();
                }
            }

            @Override
            protected void done() {
                try {
                    JsonArray datos = get();
                    modelo.setRowCount(0);
                    for (JsonElement el : datos) {
                        JsonObject p = el.getAsJsonObject();

                        int id = p.has("id") ? p.get("id").getAsInt() : 0;

                        // C# envía los campos del DTO como camelCase al JSON
                        String unidad = p.has("unidadMedida") ? p.get("unidadMedida").getAsString() : "N/A";
                        int stock = p.has("stockActual") ? p.get("stockActual").getAsInt() : 0;

                        modelo.addRow(new Object[]{
                            id,
                            gs(p, "nombre"), 
                            gs(p, "tipoProducto"),
                            unidad, // <--- UNIDAD REAL
                            gs(p, "precio"),
                            gs(p, "fechaVencimiento"), 
                            gs(p, "estado"), 
                            stock   // <--- STOCK REAL
                        });
                    }
                } catch (Exception ex) { ex.printStackTrace(); }
            }
        }.execute();
    }

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        // TODO add your handling code here:
        String txt = txtBuscador.getText().trim();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        jTable1.setRowSorter(sorter);
        sorter.setRowFilter(txt.isEmpty() ? null : RowFilter.regexFilter("(?i)" + txt, 1));
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        txtBuscadorActionPerformed(evt);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        ProductoFormDialog d = new ProductoFormDialog((Frame) SwingUtilities.getWindowAncestor(this), true, null);
        d.setVisible(true);
        if (d.isGuardado()) cargarProductos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Selecciona un producto."); return; }
        int id = (int) modelo.getValueAt(jTable1.convertRowIndexToModel(row), 0);
        ProductoFormDialog d = new ProductoFormDialog((Frame) SwingUtilities.getWindowAncestor(this), true, id);
        d.setVisible(true);
        if (d.isGuardado()) cargarProductos();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Selecciona un producto."); return; }
        int id   = (int)    modelo.getValueAt(jTable1.convertRowIndexToModel(row), 0);
        String n = (String) modelo.getValueAt(jTable1.convertRowIndexToModel(row), 1);
        if (JOptionPane.showConfirmDialog(this, "¿Eliminar: " + n + "?", "Confirmar",
                JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) return;
        new SwingWorker<Void, Void>() {
            String err;
            @Override protected Void doInBackground() {
                try { ApiClient.delete("/productos/" + id); }
                catch (Exception ex) { err = ex.getMessage(); }
                return null;
            }
            @Override protected void done() {
                if (err != null) JOptionPane.showMessageDialog(BodegaPanel.this, "Error: " + err);
                else { JOptionPane.showMessageDialog(BodegaPanel.this, "Eliminado."); cargarProductos(); }
            }
        }.execute();
    }//GEN-LAST:event_btnEliminarActionPerformed
    private String gs(JsonObject o, String k) {
        return (o.has(k) && !o.get(k).isJsonNull())
                ? o.get(k).getAsString()
                : "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables
}
