package com.hospital.swing.bodega;

import com.google.gson.*;
import com.hospital.swing.api.ApiClient;
import javax.swing.*;
import java.awt.*;

public class ProductoFormDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = 
    java.util.logging.Logger.getLogger(ProductoFormDialog.class.getName());
    
    private boolean guardado = false;
    private Integer idProducto;

    public ProductoFormDialog(java.awt.Frame parent, boolean modal, Integer idProducto) {
        super(parent, modal);
        this.idProducto = idProducto;
        initComponents();
        setTitle(idProducto == null ? "Nuevo Producto" : "Editar Producto");
        setLocationRelativeTo(parent);
        cargarEstados();
        if (idProducto != null) cargarDatos();
    }

    public boolean isGuardado() { return guardado; }

    private void cargarEstados() {
        cmbEstado.removeAllItems();
        cmbEstado.addItem("Activo");
        cmbEstado.addItem("Inactivo");
        cmbEstado.addItem("Por vencer");
        cmbEstado.addItem("Agotado");
    }

    private void cargarDatos() {
        new SwingWorker<JsonObject, Void>() {
            @Override
            protected JsonObject doInBackground() throws Exception {
                // El endpoint de C# suele ser /api/productos/{id}
                JsonElement r = ApiClient.get("/productos/" + idProducto);
                return r.isJsonObject() ? r.getAsJsonObject() : null;
            }
            @Override
            protected void done() {
                try {
                    JsonObject p = get();
                    if (p == null) return;
                    // Mapeo flexible para nombres de C# (Mayúscula o minúscula)
                    txtNombre.setText(gs(p, "nombre"));
                    txtTipo.setText(gs(p, "tipoProducto"));
                    txtUnidad.setText(gs(p, "unidadMedida"));
                    txtPrecio.setText(gs(p, "precio")); 
                    txtFechaVencimiento.setText(gs(p, "fechaVencimiento"));
                    txtUbicacion.setText(gs(p, "ubicacion"));
                    cmbEstado.setSelectedItem(gs(p, "estado"));
                    
                    // Cargar stock actual del producto
                    int stock = p.has("stockActual") ? p.get("stockActual").getAsInt() : 0;
                    txtStockActual.setText(String.valueOf(stock));
                } catch (Exception ex) { ex.printStackTrace(); }
            }
        }.execute();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtUnidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtFechaVencimiento = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        txtStockActual = new javax.swing.JTextField();
        txtStockMinimo = new javax.swing.JTextField();
        txtStockMaximo = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNombre.setText("Nombre");
        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtTipo.setText("Tipo");
        txtTipo.addActionListener(this::txtTipoActionPerformed);

        txtUnidad.setText("Unidad");
        txtUnidad.addActionListener(this::txtUnidadActionPerformed);

        txtPrecio.setText("Precio");
        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        txtFechaVencimiento.setText("Fecha de Vencimiento");
        txtFechaVencimiento.addActionListener(this::txtFechaVencimientoActionPerformed);

        txtUbicacion.setText("Ubicación");
        txtUbicacion.addActionListener(this::txtUbicacionActionPerformed);

        txtStockActual.setText("Stock actual");
        txtStockActual.addActionListener(this::txtStockActualActionPerformed);

        txtStockMinimo.setText("Stock mínimo");
        txtStockMinimo.addActionListener(this::txtStockMinimoActionPerformed);

        txtStockMaximo.setText("Stock máximo");
        txtStockMaximo.addActionListener(this::txtStockMaximoActionPerformed);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEstado.addActionListener(this::cmbEstadoActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(txtTipo)
                                .addComponent(txtUnidad)
                                .addComponent(txtPrecio))
                            .addComponent(txtFechaVencimiento)
                            .addComponent(txtUbicacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtStockActual)
                            .addComponent(txtStockMinimo)
                            .addComponent(txtStockMaximo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void txtUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtFechaVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaVencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaVencimientoActionPerformed

    private void txtUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUbicacionActionPerformed

    private void txtStockActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActualActionPerformed

    private void txtStockMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockMinimoActionPerformed

    private void txtStockMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockMaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockMaximoActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
            return;
        }

        btnGuardar.setEnabled(false);

        new SwingWorker<Void, Void>() {
            String err;
            @Override
            protected Void doInBackground() {
                try {
                    JsonObject p = new JsonObject();
                    // Nombres que espera el DTO de C#
                    p.addProperty("Nombre",           txtNombre.getText().trim());
                    p.addProperty("TipoProducto",     txtTipo.getText().trim());
                    p.addProperty("UnidadMedida",     txtUnidad.getText().trim());
                    p.addProperty("Precio",           Double.parseDouble(txtPrecio.getText().trim()));
                    p.addProperty("FechaVencimiento", txtFechaVencimiento.getText().trim());
                    p.addProperty("Estado",           cmbEstado.getSelectedItem().toString());

                    JsonElement resp;
                    if (idProducto == null) {
                        resp = ApiClient.post("/productos", p);
                    } else {
                        p.addProperty("Id", idProducto);
                        resp = ApiClient.put("/productos/" + idProducto, p);
                    }

                    // --- SOLUCIÓN AL ERROR DEL NULL ---
                    int resolvedId = 0;
                    if (idProducto != null) {
                        resolvedId = idProducto;
                    } else {
                        JsonObject responseObj = resp.getAsJsonObject();
                        // Intentar obtener el ID con las llaves que C# suele usar
                        if (responseObj.has("id")) resolvedId = responseObj.get("id").getAsInt();
                        else if (responseObj.has("Id")) resolvedId = responseObj.get("Id").getAsInt();
                        else if (responseObj.has("idProducto")) resolvedId = responseObj.get("idProducto").getAsInt();
                    }

                    // Guardar datos técnicos en Inventario
                    // --- REEMPLAZA ESTE BLOQUE DENTRO DEL doInBackground ---

                    // Preparamos el objeto para el movimiento de inventario inicial
                    JsonObject mov = new JsonObject();
                    mov.addProperty("IdProducto", resolvedId); 
                    // Cambiamos "StockActual" por "Cantidad", que es lo que el DTO de C# espera
                    mov.addProperty("Cantidad", Integer.parseInt(txtStockActual.getText().trim()));
                    // Agregamos los campos obligatorios que el servidor pide (Error 400)
                    mov.addProperty("TipoMovimiento", "ENTRADA"); 
                    mov.addProperty("Motivo", "Registro inicial de stock");

                    // Enviamos la petición al endpoint correcto
                    try {
                        // Usamos la ruta /inventario/movimiento que definimos en C#
                        ApiClient.post("/inventario/movimiento", mov);
                    } catch (Exception ex) {
                        System.err.println("Error al registrar stock inicial: " + ex.getMessage());
                        // No lanzamos error para que al menos el producto se cree, 
                        // aunque puedes manejarlo según prefieras.
                    }
                } catch (Exception ex) { 
                    err = ex.getMessage(); 
                }
                return null;
            }
            @Override
            protected void done() {
                btnGuardar.setEnabled(true);
                if (err != null) {
                    JOptionPane.showMessageDialog(ProductoFormDialog.this, "Error: " + err);
                } else {
                    guardado = true;
                    dispose();
                }
            }
        }.execute(); 
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    private String gs(JsonObject o, String k) {
        if (o.has(k) && !o.get(k).isJsonNull()) return o.get(k).getAsString();
        // Probar con Mayúscula inicial (PascalCase de C#)
        
        String capitalized = k.substring(0, 1).toUpperCase() + k.substring(1);
        if (o.has(capitalized) && !o.get(capitalized).isJsonNull()) return o.get(capitalized).getAsString();
        return "";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ProductoFormDialog dialog = new ProductoFormDialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStockActual;
    private javax.swing.JTextField txtStockMaximo;
    private javax.swing.JTextField txtStockMinimo;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtUbicacion;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
