package com.hospital.swing.administracion;

import com.google.gson.*;
import com.hospital.swing.api.ApiClient;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.io.*;
import java.nio.file.*;

public class FinancieroPanel extends javax.swing.JPanel {

    private DefaultTableModel modelo;

    public FinancieroPanel() {
        initComponents();
        configurarTabla();
        cargarDatos();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnExportar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));

        jLabel1.setText("Total Consultas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));

        jLabel2.setText("Ingresos $");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        jLabel3.setText("Stock Bajo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnExportar.setText("Exportar Reporte");
        btnExportar.addActionListener(this::btnExportarActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Registro Financiero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExportar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExportar)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla() {
        modelo = new DefaultTableModel(
            new String[]{"ID", "Paciente", "Médico", "Fecha", "Diagnóstico", "Costo"}, 0
        ) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        jTable1.setModel(modelo);
        jTable1.setRowHeight(26);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setBackground(new Color(30, 80, 150));
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.setAutoCreateRowSorter(true);
    }
    public void cargarDatos() {
        new SwingWorker<Void, Void>() {
            JsonArray consultasArr = new JsonArray();
            JsonArray inventarioArr = new JsonArray();

            @Override 
            protected Void doInBackground() {
                try {
                    JsonElement resC = ApiClient.get("/consultas");
                    System.out.println("DEBUG Financiero - Consultas: " + resC.toString());
                    if (resC.isJsonArray()) consultasArr = resC.getAsJsonArray();
                } catch (Exception e) { 
                    System.err.println("Error Financiero (Consultas): " + e.getMessage()); 
                }

                try {
                    JsonElement resI = ApiClient.get("/inventario/status");
                    System.out.println("DEBUG Financiero - Inventario: " + resI.toString());
                    if (resI.isJsonArray()) inventarioArr = resI.getAsJsonArray();
                } catch (Exception e) { 
                    System.err.println("Error Financiero (Inventario): " + e.getMessage()); 
                }
                return null;
            }

            @Override 
            protected void done() {
                modelo.setRowCount(0);
                double totalIngresos = 0;
                int contadorStockBajo = 0;

                for (JsonElement el : consultasArr) {
                    JsonObject c = el.getAsJsonObject();

                    int id = c.has("id") ? c.get("id").getAsInt() : 0;
                    String pac = c.has("nombrePaciente") ? c.get("nombrePaciente").getAsString() : "";
                    String med = c.has("nombreMedico") ? c.get("nombreMedico").getAsString() : "";
                    String fch = c.has("fecha") ? c.get("fecha").getAsString() : "";
                    String dia = c.has("diagnostico") ? c.get("diagnostico").getAsString() : "";
                    double cos = c.has("costo") ? c.get("costo").getAsDouble() : 0.0;

                    totalIngresos += cos;

                    modelo.addRow(new Object[]{ id, pac, med, fch, dia, String.format("$%.2f", cos) });
                }

                for (JsonElement el : inventarioArr) {
                    JsonObject i = el.getAsJsonObject();
                    // Nombres exactos de tu JSON: stockActual, stockMinimo
                    int actual = i.has("stockActual") ? i.get("stockActual").getAsInt() : 0;
                    int minimo = i.has("stockMinimo") ? i.get("stockMinimo").getAsInt() : 0;

                    if (actual <= minimo) {
                        contadorStockBajo++;
                    }
                }

                jLabel1.setText("Total Consultas: " + consultasArr.size());
                jLabel2.setText(String.format("Ingresos: $%.2f", totalIngresos));
                jLabel3.setText("Stock Bajo: " + contadorStockBajo);
            }
        }.execute();
    }
    
    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        try {
            StringBuilder sb = new StringBuilder();
            sb.append("REPORTE FINANCIERO - Sistema Hospitalario\n");
            sb.append("==========================================\n\n");
            sb.append(jLabel1.getText()).append("\n"); // Total Consultas
            sb.append(jLabel2.getText()).append("\n"); // Ingresos
            sb.append(jLabel3.getText()).append("\n\n"); // Stock Bajo

            sb.append("ID | Paciente | Médico | Fecha | Diagnóstico | Costo\n");
            sb.append("----------------------------------------------------\n");

            for (int r = 0; r < modelo.getRowCount(); r++) {
                for (int c = 0; c < modelo.getColumnCount(); c++) {
                    Object valor = modelo.getValueAt(r, c);
                    sb.append(valor != null ? valor.toString() : "");
                    if (c < modelo.getColumnCount() - 1) sb.append(" | ");
                }
                sb.append("\n");
            }

            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Guardar Reporte Financiero");
            fc.setSelectedFile(new File("reporte_financiero.txt"));

            if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                File archivo = fc.getSelectedFile();

                java.nio.file.Files.write(
                    archivo.toPath(), 
                    sb.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8)
                );

                JOptionPane.showMessageDialog(this, "Reporte exportado correctamente en:\n" + archivo.getAbsolutePath());
            }
        } catch (java.io.IOException ex) {
            JOptionPane.showMessageDialog(this, "Error de escritura: " + ex.getMessage() + 
                    "\nIntenta guardar el archivo en el Escritorio o una carpeta fuera de OneDrive.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private String gs(JsonObject o, String k) {
        return (o.has(k) && !o.get(k).isJsonNull()) ? o.get(k).getAsString() : "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
