package com.hospital.swing.administracion;

import com.google.gson.*;
import com.hospital.swing.api.ApiClient;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;

public class InventarioAdminPanel extends javax.swing.JPanel {

    private DefaultTableModel modelo;

    public InventarioAdminPanel() {
        initComponents();
        configurarTabla();
        cargarInventario();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblResumen = new javax.swing.JLabel();

        jLabel1.setText("Inventario");

        btnRegistrar.setText("Registrar Movimiento");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblResumen.setText("Resumen de stock bajo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResumen)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnActualizar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnActualizar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResumen)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla() {
        modelo = new DefaultTableModel(
            new String[]{"ID", "Producto", "Stock Actual", "Stock Mín.", "Stock Máx.", "Última Act."}, 0
        ) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        jTable1.setModel(modelo);
        jTable1.setRowHeight(26);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setBackground(new Color(30, 80, 150));
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.setAutoCreateRowSorter(true);

        // Colorear filas con stock bajo
        jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    JTable t, Object v, boolean sel, boolean foc, int r, int c) {
                super.getTableCellRendererComponent(t, v, sel, foc, r, c);
                int row = t.convertRowIndexToModel(r);
                try {
                    int actual = Integer.parseInt(modelo.getValueAt(row, 2).toString());
                    int minimo = Integer.parseInt(modelo.getValueAt(row, 3).toString());
                    if (!sel) setBackground(actual <= minimo
                        ? new Color(255, 200, 200) : Color.WHITE);
                } catch (Exception ignored) {
                    if (!sel) setBackground(Color.WHITE);
                }
                return this;
            }
        });
    }

    public void cargarInventario() {
        new SwingWorker<JsonArray, Void>() {
            @Override protected JsonArray doInBackground() {
                try {
                    JsonElement r = ApiClient.get("/inventario/status");
                    // Mira este print en la consola, te dirá EXACTAMENTE cómo vienen las llaves
                    System.out.println("DEBUG JSON RECIBIDO: " + r.toString()); 
                    return r.isJsonArray() ? r.getAsJsonArray() : new JsonArray();
                } catch (Exception ex) { 
                    System.err.println("Error al cargar inventario: " + ex.getMessage());
                    return new JsonArray(); 
                }
            }

            @Override
            protected void done() {
                try {
                    JsonArray datos = get();
                    modelo.setRowCount(0);
                    int stockBajo = 0;

                    for (JsonElement el : datos) {
                        JsonObject i = el.getAsJsonObject();

                        // 1. EXTRAER ID (Buscando todas las variantes de C#)
                        int id = 0;
                        if (i.has("idInventario")) id = i.get("idInventario").getAsInt();
                        else if (i.has("IdInventario")) id = i.get("IdInventario").getAsInt();
                        else if (i.has("idProducto")) id = i.get("idProducto").getAsInt();
                        else if (i.has("IdProducto")) id = i.get("IdProducto").getAsInt();

                        // 2. EXTRAER STOCK ACTUAL
                        int actual = 0;
                        if (i.has("stockActual")) actual = i.get("stockActual").getAsInt();
                        else if (i.has("StockActual")) actual = i.get("StockActual").getAsInt();

                        // 3. EXTRAER STOCK MÍNIMO
                        int minimo = 0;
                        if (i.has("stockMinimo")) minimo = i.get("stockMinimo").getAsInt();
                        else if (i.has("StockMinimo")) minimo = i.get("StockMinimo").getAsInt();

                        // 4. EXTRAER STOCK MÁXIMO
                        int maximo = 0;
                        if (i.has("stockMaximo")) maximo = i.get("stockMaximo").getAsInt();
                        else if (i.has("StockMaximo")) maximo = i.get("StockMaximo").getAsInt();

                        // 5. EXTRAER NOMBRE PRODUCTO
                        String nombreProd = "Sin nombre";
                        if (i.has("nombreProducto")) nombreProd = i.get("nombreProducto").getAsString();
                        else if (i.has("NombreProducto")) nombreProd = i.get("NombreProducto").getAsString();

                        // 6. Lógica de Stock Bajo
                        if (actual <= minimo) stockBajo++;

                        // 7. Agregar a la tabla
                        modelo.addRow(new Object[]{
                            id,
                            nombreProd, 
                            actual, 
                            minimo,
                            maximo,
                            gs(i, "fechaActualizacion") 
                        });
                    }
                    actualizarResumen(stockBajo);
                } catch (Exception ex) { 
                    ex.printStackTrace();
                }
            }
        }.execute();
    }

    private void actualizarResumen(int stockBajo) {
        lblResumen.setText(stockBajo > 0
            ? "⚠ " + stockBajo + " producto(s) con stock bajo (fila roja)"
            : "✓ Todos los productos tienen stock suficiente");
        lblResumen.setForeground(stockBajo > 0
            ? new Color(180, 40, 40) : new Color(34, 139, 34));
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        Integer idInv = null;

        // Si hay una fila seleccionada, obtenemos el ID de la columna 0
        if (row >= 0) {
            int modelRow = jTable1.convertRowIndexToModel(row);
            idInv = (Integer) modelo.getValueAt(modelRow, 0);
        }

        // Abrimos el diálogo. Pasamos 'null' si no hay selección, 
        // y el diálogo corregido debería permitir elegir un producto.
        Window parentWindow = SwingUtilities.getWindowAncestor(this);
        MovimientoDialog d = new MovimientoDialog((Frame)parentWindow, true, idInv);
        d.setVisible(true);

        if (d.isRegistrado()) {
            cargarInventario(); // Recargar la tabla si se guardó algo
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cargarInventario();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private String gs(JsonObject o, String k) {
        return (o.has(k) && !o.get(k).isJsonNull()) ? o.get(k).getAsString() : "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblResumen;
    // End of variables declaration//GEN-END:variables
}
