package com.hospital.swing.administracion;

import com.google.gson.*;
import com.hospital.swing.api.ApiClient;
import com.hospital.swing.session.SessionManager;
import javax.swing.*;
import java.awt.*;

public class MovimientoDialog extends JDialog {

    private boolean registrado = false;
    private Integer idInventarioPreseleccionado;

    public MovimientoDialog(Frame parent, boolean modal, Integer idInventario) {
        super(parent, modal);
        this.idInventarioPreseleccionado = idInventario;
        initComponents();
        configurarCombos();
        cargarProductos(); 
        setTitle("Registrar Movimiento de Inventario");
        setLocationRelativeTo(parent);
    }

    public boolean isRegistrado() {
        return registrado;
    }

    private void configurarCombos() {
        cmbTipo.setModel(new DefaultComboBoxModel<>(new String[]{"ENTRADA", "SALIDA"}));
    }

    private void cargarProductos() {
        new SwingWorker<JsonArray, Void>() {
            @Override
            protected JsonArray doInBackground() throws Exception {
                JsonElement r = ApiClient.get("/inventario/status");
                return r.isJsonArray() ? r.getAsJsonArray() : new JsonArray();
            }

            @Override
            protected void done() {
                try {
                    JsonArray data = get();
                    DefaultComboBoxModel<Object> model = new DefaultComboBoxModel<>();
                    
                    for (JsonElement el : data) {
                        JsonObject obj = el.getAsJsonObject();

                        // Extracción robusta de ID
                        int idEncontrado = 0;
                        if (obj.has("idProducto")) idEncontrado = obj.get("idProducto").getAsInt();
                        else if (obj.has("IdProducto")) idEncontrado = obj.get("IdProducto").getAsInt();
                        else if (obj.has("idInventario")) idEncontrado = obj.get("idInventario").getAsInt();
                        else if (obj.has("IdInventario")) idEncontrado = obj.get("IdInventario").getAsInt();

                        // Extracción robusta de Nombre
                        String nombre = "ID: " + idEncontrado;
                        if (obj.has("nombreProducto")) nombre = obj.get("nombreProducto").getAsString();
                        else if (obj.has("NombreProducto")) nombre = obj.get("NombreProducto").getAsString();

                        InventarioItem itemParaCombo = new InventarioItem(idEncontrado, nombre);
                        model.addElement(itemParaCombo);
                        
                        if (idInventarioPreseleccionado != null && idEncontrado == idInventarioPreseleccionado) {
                            model.setSelectedItem(itemParaCombo);
                        }
                    }
                    cmbProductos.setModel((DefaultComboBoxModel) model);
                } catch (Exception ex) {
                    System.err.println("Error en combo: " + ex.getMessage());
                }
            }
        }.execute();
    }
    private static class InventarioItem {
        int id;
        String nombre;
        InventarioItem(int id, String nombre) { this.id = id; this.nombre = nombre; }
        @Override public String toString() { return nombre; }
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTipo = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        txtMotivo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbProductos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipo.addActionListener(this::cmbTipoActionPerformed);

        txtCantidad.setText("Cantidad");
        txtCantidad.addActionListener(this::txtCantidadActionPerformed);

        txtMotivo.setText("Motivo");
        txtMotivo.addActionListener(this::txtMotivoActionPerformed);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        cmbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProductos.addActionListener(this::cmbProductosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRegistrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtCantidad)
                            .addGap(18, 18, 18)
                            .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       
    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotivoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        Object itemObj = cmbProductos.getSelectedItem();
        if (!(itemObj instanceof InventarioItem)) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la lista.");
            return;
        }

        InventarioItem selected = (InventarioItem) itemObj;
        
        // Validación de seguridad para el ID
        if (selected.id <= 0) {
            JOptionPane.showMessageDialog(this, "Error: El ID del producto es 0. Verifique la base de datos.");
            return;
        }

        String cantStr = txtCantidad.getText().trim();
        int cantidad;
        try {
            cantidad = Integer.parseInt(cantStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cantidad inválida.");
            return;
        }

        String tipo = cmbTipo.getSelectedItem().toString();
        String motivo = txtMotivo.getText().trim();

        btnRegistrar.setEnabled(false);

        new SwingWorker<Void, Void>() {
            String err;
            @Override protected Void doInBackground() {
                try {
                    JsonObject mov = new JsonObject();
                    // Sincronizado exactamente con el DTO de C#
                    mov.addProperty("IdProducto", selected.id); 
                    mov.addProperty("Cantidad", cantidad);
                    mov.addProperty("TipoMovimiento", tipo);
                    mov.addProperty("Motivo", motivo);

                    ApiClient.post("/inventario/movimiento", mov);
                } catch (Exception ex) { err = ex.getMessage(); }
                return null;
            }
            @Override protected void done() {
                btnRegistrar.setEnabled(true);
                if (err != null) JOptionPane.showMessageDialog(MovimientoDialog.this, "Error: " + err);
                else { 
                    registrado = true; 
                    JOptionPane.showMessageDialog(MovimientoDialog.this, "Movimiento registrado con éxito.");
                    dispose(); 
                }
            }
        }.execute();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductosActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> {
            MovimientoDialog dialog =
                    new MovimientoDialog(new javax.swing.JFrame(), true, 1); // ← ID de prueba

            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });

            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables
}
