package com.hospital.swing.administracion;

import com.google.gson.*;
import com.hospital.swing.api.ApiClient;
import javax.swing.*;

public class UsuarioFormDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(UsuarioFormDialog.class.getName());

    private boolean guardado = false;
    private Integer idUsuario;

    public UsuarioFormDialog(java.awt.Frame parent, boolean modal, Integer idUsuario) {
        super(parent, modal);
        this.idUsuario = idUsuario;
        initComponents();
        setTitle(idUsuario == null ? "Nuevo Usuario" : "Editar Usuario");
        setLocationRelativeTo(parent);
        cargarRoles();
        if (idUsuario != null) cargarDatos();
    }

    public boolean isGuardado() { return guardado; }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        cmbRol = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNombre.setText("Nombre Completo");
        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtUsuario.setText("Usuario");
        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);

        txtPassword.setText("Contraseña");
        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRol.addActionListener(this::cmbRolActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(txtNombre)
                    .addComponent(txtUsuario)
                    .addComponent(txtPassword)
                    .addComponent(cmbRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private java.util.Map<String, Integer> mapaRoles = new java.util.HashMap<>();

    private void cargarRoles() {

        new javax.swing.SwingWorker<com.google.gson.JsonArray, Void>() {

            @Override
            protected com.google.gson.JsonArray doInBackground() {
                try {
                    com.google.gson.JsonElement r = ApiClient.get("/roles");
                    return r.isJsonArray() ? r.getAsJsonArray() : new com.google.gson.JsonArray();
                } catch (Exception e) {
                    e.printStackTrace();
                    return new com.google.gson.JsonArray();
                }
            }

            @Override
            protected void done() {
                try {
                    cmbRol.removeAllItems();
                    mapaRoles.clear();

                    for (com.google.gson.JsonElement el : get()) {
                        com.google.gson.JsonObject obj = el.getAsJsonObject();

                        int id = obj.get("id").getAsInt();      // ✅ CORRECTO
                        String nombre = obj.get("nombre").getAsString();

                        cmbRol.addItem(nombre);
                        mapaRoles.put(nombre, id);
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        }.execute();
    }

    private void cargarDatos() {
        new SwingWorker<JsonObject, Void>() {
            @Override protected JsonObject doInBackground() throws Exception {
                JsonElement r = ApiClient.get("/usuarios/" + idUsuario);
                return r.isJsonObject() ? r.getAsJsonObject() : null;
            }
            @Override protected void done() {
                try {
                    JsonObject u = get();
                    if (u == null) return;
                    txtNombre.setText(gs(u, "nombre"));
                    txtUsuario.setText(gs(u, "usuario"));
                    txtPassword.setText("");  // no precargar contraseña
                    cmbRol.setSelectedItem(gs(u, "rol"));
                } catch (Exception ex) { ex.printStackTrace(); }
            }
        }.execute();
    }
    
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (txtNombre.getText().trim().isEmpty() || txtUsuario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombre y usuario son obligatorios.");
            return;
        }
        btnGuardar.setEnabled(false);
        new SwingWorker<Void, Void>() {
            String err;
            @Override protected Void doInBackground() {
                try {
                    JsonObject u = new JsonObject();
                    u.addProperty("nombre",  txtNombre.getText().trim());
                    u.addProperty("usuario", txtUsuario.getText().trim());
                    // 🔥 Obtener el ID real del rol
                    String rolSeleccionado = cmbRol.getSelectedItem().toString();
                    Integer idRol = mapaRoles.get(rolSeleccionado);

                    System.out.println("Rol seleccionado: " + rolSeleccionado);
                    System.out.println("IdRol enviado: " + idRol);

                    if (idRol == null) {
                        throw new RuntimeException("El rol seleccionado no es válido.");
                    }

                    u.addProperty("idRol", idRol);
                    String pwd = new String(txtPassword.getPassword()).trim();
                    if (!pwd.isEmpty()) u.addProperty("contraseña", pwd);
                    
                    if (idUsuario == null) {
                        ApiClient.post("/usuarios/register", u);
                    } else {
                        u.addProperty("idUsuario", idUsuario);
                        ApiClient.put("/usuarios/" + idUsuario, u);
                    }
                } catch (Exception ex) { err = ex.getMessage(); }
                return null;
            }
            @Override protected void done() {
                btnGuardar.setEnabled(true);
                if (err != null) JOptionPane.showMessageDialog(UsuarioFormDialog.this, "Error: " + err);
                else { guardado = true; dispose(); }
            }
        }.execute();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private String gs(JsonObject o, String k) {
        return (o.has(k) && !o.get(k).isJsonNull()) ? o.get(k).getAsString() : "";
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> {
            UsuarioFormDialog dialog =
                    new UsuarioFormDialog(new javax.swing.JFrame(), true, null);

            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });

            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
