package com.hospital.swing.administracion;

import com.google.gson.*;
import com.hospital.swing.api.ApiClient;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;

public class UsuariosPanel extends javax.swing.JPanel {

    private DefaultTableModel modelo;

    public UsuariosPanel() {
        initComponents();
        configurarTabla();
        cargarUsuarios();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Usuarios");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrar)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar)
                    .addComponent(btnBorrar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
private void configurarTabla() {
        modelo = new DefaultTableModel(
            new String[]{"ID", "Nombre", "Usuario", "Rol", "Estado"}, 0
        ) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        jTable1.setModel(modelo);
        jTable1.setRowHeight(26);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setBackground(new Color(30, 80, 150));
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.setAutoCreateRowSorter(true);
    }

    public void cargarUsuarios() {
        new SwingWorker<JsonArray, Void>() {
            @Override
            protected JsonArray doInBackground() {
                try {
                    JsonElement r = ApiClient.get("/usuarios");
                    return r.isJsonArray() ? r.getAsJsonArray() : new JsonArray();
                } catch (Exception ex) { return new JsonArray(); }
            }
            @Override
            protected void done() {
                try {
                    modelo.setRowCount(0);
                    for (JsonElement el : get()) {
                        JsonObject u = el.getAsJsonObject();
                        modelo.addRow(new Object[]{
                            u.get("id").getAsInt(),
                            gs(u, "nombre"),
                            gs(u, "usuario"),
                            gs(u, "nombreRol"),
                            ""
                        });
                    }
                } catch (Exception ex) { ex.printStackTrace(); }
            }
        }.execute();
    }
    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row < 0) { 
            JOptionPane.showMessageDialog(this, "Selecciona un usuario."); 
            return; 
        }
        int    id = (int)    modelo.getValueAt(jTable1.convertRowIndexToModel(row), 0);
        String n  = (String) modelo.getValueAt(jTable1.convertRowIndexToModel(row), 1);
        
        if (JOptionPane.showConfirmDialog(this, "¿Eliminar usuario: " + n + "?",
                "Confirmar", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) return;
        new SwingWorker<Void, Void>() {
            String err;
            @Override protected Void doInBackground() {
                try { ApiClient.delete("/usuarios/" + id); }
                catch (Exception ex) { err = ex.getMessage(); }
                return null;
            }
            @Override protected void done() {
                if (err != null) JOptionPane.showMessageDialog(UsuariosPanel.this, "Error: " + err);
                else { JOptionPane.showMessageDialog(UsuariosPanel.this, "Usuario eliminado."); cargarUsuarios(); }
            }
        }.execute();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Selecciona un usuario."); return; }
        int id = (int) modelo.getValueAt(jTable1.convertRowIndexToModel(row), 0);
        UsuarioFormDialog d = new UsuarioFormDialog(
            (Frame) SwingUtilities.getWindowAncestor(this), true, id);
        d.setVisible(true);
        if (d.isGuardado()) cargarUsuarios();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        UsuarioFormDialog d = new UsuarioFormDialog(
            (Frame) SwingUtilities.getWindowAncestor(this), true, null);
        d.setVisible(true);
        if (d.isGuardado()) cargarUsuarios();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private String gs(JsonObject o, String k) {
        return (o.has(k) && !o.get(k).isJsonNull()) ? o.get(k).getAsString() : "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
